<template>
  <div class="p-6">
    <div class="flex items-center justify-between mb-6">
      <div>
        <h1 class="text-2xl font-bold text-gray-900 dark:text-white">
          {{ t('logs.title', 'System logs') }}
        </h1>
        <p class="text-gray-500 dark:text-gray-400 mt-1 text-sm">
          {{ t('logs.description', 'Error and warning logs generated by background processes') }}
        </p>
      </div>
      <u-button
        icon="i-heroicons-trash"
        color="error"
        variant="outline"
        :loading="purging"
        @click="purgeAll"
      >
        {{ t('logs.purge_all', 'Purge all') }}
      </u-button>
    </div>

    <!-- Settings card -->
    <u-card class="mb-6 max-w-2xl">
      <template #header>
        <div class="flex items-center gap-2">
          <u-icon
            class="text-primary-500"
            name="i-heroicons-cog-6-tooth"
          />
          <h2 class="font-semibold text-gray-900 dark:text-white">
            {{ t('logs.settings_title', 'Auto-purge settings') }}
          </h2>
        </div>
      </template>
      <div
        v-if="settingsPending"
        class="space-y-3"
      >
        <u-skeleton class="h-8" />
        <u-skeleton class="h-8" />
      </div>
      <div
        v-else
        class="space-y-4"
      >
        <u-form-field :label="t('logs.retention_days_label', 'Retain logs for (days)')">
          <u-input
            v-model="retentionDays"
            type="number"
            :min="1"
            :max="365"
            class="w-40"
          />
        </u-form-field>
        <u-form-field :label="t('logs.purge_interval_label', 'Auto-purge interval (hours)')">
          <u-input
            v-model="purgeIntervalHours"
            type="number"
            :min="1"
            :max="720"
            class="w-40"
          />
        </u-form-field>
        <div class="flex justify-end">
          <u-button
            :loading="savingSettings"
            @click="onSaveSettings"
          >
            {{ t('common.save', 'Save') }}
          </u-button>
        </div>
      </div>
    </u-card>

    <!-- Filters -->
    <div class="flex gap-3 mb-4">
      <u-selectMenu
        v-model="filterLevel"
        :items="levelOptions"
        value-key="value"
        class="w-36"
        @update:model-value="refresh"
      />
      <u-input
        v-model="filterContext"
        :placeholder="t('logs.filter_context', 'Filter by context...')"
        icon="i-heroicons-magnifying-glass"
        class="flex-1 max-w-xs"
        @input="debouncedRefresh"
      />
      <u-button
        variant="outline"
        color="neutral"
        icon="i-heroicons-arrow-path"
        :loading="pending"
        @click="refresh"
      >
        {{ t('common.refresh', 'Refresh') }}
      </u-button>
    </div>

    <!-- Empty state -->
    <div
      v-if="!pending && !data?.data?.length"
      class="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 py-16 text-center"
    >
      <u-icon
        name="i-heroicons-check-circle"
        class="text-5xl text-green-400 mb-3"
      />
      <p class="text-gray-500 font-medium">
        {{ t('logs.empty', 'No logs found') }}
      </p>
    </div>

    <!-- Logs table -->
    <div
      v-else
      class="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 overflow-hidden"
    >
      <!-- Loading -->
      <div
        v-if="pending"
        class="space-y-0"
      >
        <div
          v-for="i in 8"
          :key="i"
          class="px-4 py-3 border-b border-gray-100 dark:border-gray-800 last:border-0"
        >
          <u-skeleton class="h-4 w-full" />
        </div>
      </div>

      <!-- Rows -->
      <div v-else>
        <div
          v-for="log in data.data"
          :key="log.id"
          class="px-4 py-3 border-b border-gray-100 dark:border-gray-800 last:border-0 hover:bg-gray-50 dark:hover:bg-gray-800/50"
        >
          <div class="flex items-start gap-3">
            <span
              class="shrink-0 mt-0.5 inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold"
              :class="levelClass(log.level)"
            >
              {{ log.level }}
            </span>
            <div class="min-w-0 flex-1">
              <div class="flex items-center gap-2 mb-0.5">
                <code class="text-xs text-primary-600 dark:text-primary-400 bg-primary-50 dark:bg-primary-900/30 px-1.5 py-0.5 rounded">
                  {{ log.context }}
                </code>
                <span class="text-xs text-gray-400">{{ formatDate(log.created_at) }}</span>
              </div>
              <p class="text-sm text-gray-700 dark:text-gray-300">
                {{ log.message }}
              </p>
              <details
                v-if="log.details"
                class="mt-1"
              >
                <summary class="text-xs text-gray-400 cursor-pointer hover:text-gray-600">
                  {{ t('logs.show_details', 'Details') }}
                </summary>
                <pre class="mt-1 text-xs bg-gray-50 dark:bg-gray-800 p-2 rounded overflow-x-auto">{{ formatDetails(log.details) }}</pre>
              </details>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Pagination -->
    <div
      v-if="(data?.total || 0) > limit"
      class="flex justify-center mt-5"
    >
      <u-pagination
        v-model:page="page"
        :total="data?.total || 0"
        :items-per-page="limit"
        @update:page="refresh"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
const { currentUser } = useAuth()
const { t } = useT()
const { getLogs, purgeLogs, logsPending: pending, logsPurging: purging } = useAdmin()
const { settings, pending: settingsPending, refresh: loadSettings, saving: savingSettings, saveSettings } = useSettings()

watch(() => currentUser.value?.is_super_admin, (ok) => {
  if (import.meta.client && ok === false) navigateTo('/')
}, { immediate: true })

const filterLevel = ref('all')
const filterContext = ref('')
const page = ref(1)
const limit = 50

const levelOptions = computed(() => [
  { label: t('logs.level_all', 'All levels'), value: 'all' },
  { label: t('logs.level_error', 'Error'), value: 'error' },
  { label: t('logs.level_warn', 'Warning'), value: 'warn' },
  { label: t('logs.level_info', 'Info'), value: 'info' },
])

const data = ref<{ data: any[]; total: number } | null>(null)

async function refresh() {
  const params: Record<string, any> = { page: page.value, limit }
  if (filterLevel.value !== 'all') params.level = filterLevel.value
  if (filterContext.value) params.context = filterContext.value
  data.value = await getLogs(params)
}

let _debounceTimer: ReturnType<typeof setTimeout>
function debouncedRefresh() {
  clearTimeout(_debounceTimer)
  _debounceTimer = setTimeout(() => { page.value = 1; refresh() }, 300)
}

onMounted(refresh)

async function purgeAll() {
  await purgeLogs()
  await refresh()
}

// Settings
const retentionDays = ref('7')
const purgeIntervalHours = ref('24')

watch(settings, (s) => {
  if (s.log_retention_days) retentionDays.value = s.log_retention_days
  if (s.log_purge_interval_hours) purgeIntervalHours.value = s.log_purge_interval_hours
}, { immediate: true })

async function onSaveSettings() {
  await saveSettings({
    log_retention_days: retentionDays.value,
    log_purge_interval_hours: purgeIntervalHours.value,
  })
}

function levelClass(level: string) {
  switch (level) {
    case 'error': return 'bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-300'
    case 'warn': return 'bg-yellow-50 dark:bg-yellow-900/20 text-yellow-700 dark:text-yellow-300'
    default: return 'bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300'
  }
}

function formatDate(d: string) {
  return new Date(d).toLocaleString()
}

function formatDetails(details: string) {
  try { return JSON.stringify(JSON.parse(details), null, 2) }
  catch { return details }
}
</script>
